# Aula 4

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Definiçao alternativa de probabilidade

Existe um outro jeito de definir probabilidade em conjuntos discretos. Seja $\Omega$ um conjunto discreto, $p_i, i \geq 1$ uma sequencia de numeros positivos e $\mathcal{F}$ uma $\sigma$-álgebra de $\Omega$. Então a função 

$$ \mathbb{P}(A) = \sum_{i = 1}^\infty p_i\mathbb{I}_A(\omega_i), A \in \mathcal{F}$$

é uma medida de probabilidade se satisfizer as seguintes propriedades:

1. $\mathbb{P}(A) = \sum_{i = 1}^\infty p_i\mathbb{I}_A(\omega_i) = 1$
2. $A_1, A_2 \in \mathcal{F}$ TODO
3. Se $A_n \downarrow \emptyset$, então $\forall k \in \{1,2,...\}$, $\exists n_k$ tal que $A_n \subset \{\omega_k, \omega_{k+1},...\}$ sempre que $n \geq n_k$. Então,

$$\mathbb{P}(A_{n_k}) \leq TODO$$
## Exemplos da definição alternativa

### Exemplo 1

Seja $\Omega = \{f:\{1,..,n\} \rightarrow \{1,...,m\}\}$. Então $|\Omega| = m^n$, e a medida de probabilidade "classica" é dada fazendo $p_i = \frac{1}{m^n}$.

Queremos calcular a probabilidade do conjunto $D = \{f:f \text{ é sobrejetora}\}$, quando $m \leq n$. Para isso, tome

$$A_i = \{f \in \Omega, \exists \ j \in \{1,...,n\} \text{ tal que }f(j) = i\}$$
O conjunto das funções sobrejetoras poderá ser descrito como $D = \bigcup_{i}^m A_i$. Disso decorre que

$$\mathbb{P}(D) = \mathbb{P}\left(\bigcap_{i=1}^m A_i\right) = \mathbb{P}\left(\left( \bigcap_{i=1}^m A_i^c\right)^c\right) = 1-\mathbb{P}\left( \bigcup_{i=1}^m A_i^c\right).$$
Para desenvolver as parcelas dessa soma, basta notar que

$$\mathbb{P}(A_i^c) = \frac{|A_i^c|}{|\Omega|} = \frac{(m-1)^n}{m^n} = \left(1-\frac{1}{m}\right)^n.$$

Analogamente, essa observação pode ser estendida para as intersecções de dois, três ou mais conjuntos $A_i^c$:

$$\mathbb{P}(A_i^c \bigcap A_j^c) = \left(1-\frac{2}{m}\right)^n$$
$$\mathbb{P}(\bigcap_{i \in I}A_i^c) = \left(1-\frac{|I|}{m}\right)^n$$

Pelo princípio da inclusão e exclusão e plugando as identidades acima na equação de $\mathbb{P}(D)$, teremos:

$$\mathbb{P}(D) = 1-\mathbb{P}\left( \bigcup_{i=1}^m A_i^c \right) = 1 - \sum_{i=1}^{m} (-1)^{i+1} {m \choose i}\left(1-\frac{i}{m}\right)^n$$

### Exemplo 2

Considere uma urna com $nk$ bolinhas, sendo cada uma delas coloridas com uma dentre $k$ cores, mas com todas as cores tendo exatamente $n$ bolinhas. O experimento proposto consiste em retirar $m$ bolinhas desse Considere a medida de probabilidade uniforme nesse conjunto. Nesse contexto, queremos calcular a probabilidade do evento $D = \{\text{Pegar bolas de todas as cores}\}$. Analogamente ao realizado no exemplo anterior, considere os eventos

$$ A_i = \{\text{a i-ésima cor aparece na amostra\}}, i \in \{1,...,k\}.$$

A definição desses conjuntos permite uma nova representação do conjunto $D$:

$$D = \bigcap_{i=1}^k A_i.$$

Novamente, vamos representar a probabilidade de $D$ em termos das probabilidades de intersecções dos complementares de $A_i, i \in \{1,...,k\}$:

$$\mathbb{P}(D)=1-\mathbb{P}\left(\bigcup_{i=1}^k A_i^c \right),$$
$$\left|\bigcap_{j \in I}A_j^c \rigth| = {nk - n|I|  \choose m} = {n(k - |I|) \choose m}$$
$$\mathbb{P}\left(\bigcap_{j \in I}A_j^c\right) = \frac{|\bigcap_{j \in B}A_j^c|}{|\Omega|} = \frac{n(k - |B|) \choose m}{nk \choose m}.$$

Novamente pelo princípio de inclusão e exclusão, a probabilidade $\mathbb{P}(D)$ é

$$\mathbb{P}(D) = 1 - \mathbb{P}\left(\bigcup_{i=1}^k A_i^c \right) = 1 - \sum_{j \in B, B \in \mathcal{P}(\{1,..,k\})} (-1)^{|B|+1} \frac{n(k-|B|) \choose m}{nk \choose m}$$
### Exercício

Considere um álbum com $m$ figurinhas ditintas em que você compra $k$ delas, sorteadas aleatoriamente. Considerando que $k > m$ e que $D$ é o evento {completar a coleção}, calcule $\mathbb{P}(D)$.

## Modelo contínuo

$\Omega = \mathbb{R}$, $\mathcal{F} \in \mathcal{B}(\mathbb{R})$

Probabilidades em espaços contínuos são definidos para conjuntos $A \in \mathcal{F}$ na seguinte forma:

$$\mathbb{P}(A) = \int_A f(x)dx,$$
em que $f$ é uma função positiva.
