# Aula 5

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Modelo contínuo

Considere $\Omega = \mathbb{R}$, $\mathcal{F} \in \mathcal{B}(\mathbb{R})$ e $f: \mathbb{R}\rightarrow\mathbb{R}_+$ uma funçao contínua. Nesse contexto, probabilidades na reta são definidas para conjuntos $A \in \mathcal{F}$ na seguinte forma:

$$\mathbb{P}(A) = \int_A f(x)dx,$$
## Probabilidades condicionais

Considere o espaço de probabilidades $(\Omega, \mathcal{F}, \mathbb{P})$. Se $B \in \mathcal{F}$ e $\mathbb{P}(B)>0$, definidmos a probabilidade condicional de $A$ dado $B$ por

$$\mathbb{P}(A \ | \ B) = \frac{\mathbb{P}(A \cap B)}{\mathbb{P}(B)}$$

Essa definiçao induz o que se chama de regra do produto. Se $A_1, ..., A_n \in \mathcal{F}$ são tais que $\mathbb{P}(\bigcap_{i=1}^{n-1}A_i) > 0$, então:

$$\mathbb{P}\left(\bigcap_{i=1}^n A_i\right) = \mathbb{P}(A_1)\mathbb{P}(A_2 \ | \ A_1)\mathbb{P}(A_3 \ | \ A_2, A_1)...\mathbb{P}\left(A_n \ | \ \bigcap_{i=1}^{n-1} A_i\right)$$

A regra do produto, por sua vez, possibilida a demonstração de um teorema normalmente chamado de fórmula da probabilidade total.

### Fórmula da probabilidade total

Sejam $A_1, ..., A_n$ elementos de $\mathcal{F}$ que dividem o espaço amostral $\Omega$ em pedaços não intersectantes (em linguagem mais formal, $\cup A_i = \Omega$ e $A_i \cap A_j \neq \emptyset, \ \forall i,j$). Então, a probabilidade de qualquer conjunto $B \in \mathcal{F}$ pode ser expressa alternativamente em função dos $A_i$:

$$\mathbb{P}(B) = \sum_{i=1}^n\mathbb{P}(B|A_i)\mathbb{P}(A_i)$$
Demonstração:
 
$$\mathbb{P}(B) = \mathbb{P}(B \cap \Omega) = \mathbb{P}(B \cap (\cup A_i)) = \mathbb{P}\left(\bigcup_{i=1}^n (B \cap A_i)\right) = \sum_{i=1}^n\mathbb{P}(B \cap A_i) = \sum_{i=1}^n\mathbb{P}(B|A_i)\mathbb{P}(A_i)$$
$\blacksquare$

### Exemplo 1

Considere um experimento em que retiram-se bolas coloridas de uma urna, que contém $a$ bolas verdes e $b$ bolas brancas, devolvendo $c$ bolas da cor retirada em cada repetição do experimento. Considere o evento

$$A_i = \text{bola verde na }i-\text{ésima extração}$$

Pela regra do produto, podemos expressar a probabilidade da intersecção $A_1 \cap A_2 \cap A_3$ com a fórmula:

$$ \mathbb{P}(A_1 \cap A_2 \cap A_3) = \mathbb{P}(A_1)\mathbb{P_2}(A_2 \ | \ A_1)\mathbb{P}(A_3 \ | \ A_2, A_1) = \frac{a}{a+b}\frac{a+c}{a+b+c}\frac{a+2c}{a+b+2c}.$$

Para mostrar uma aplicação da fórmula da probabilidade total, vamos calcular $\mathbb{P}(A_3)$ utilizando esse resultado.

Considere a partição de $\Omega$ formada pelos conjuntos $B_1, B_2, B_3, B_4$, definidos abaixo.

$$B_1 = A_1 \cap A_2$$
$$B_2 = A_1 \cap A_2^c$$
$$B_3 = A_1^c \cap A_2$$
$$B_4 = A_1^c \cap A_2^c$$
Pela regra da probabilidade total, podemos expressar a probabilidade de $A_3$ em função dos conjuntos $B_i$ da seguinte forma:

$$\mathbb{P}(A_3) = \sum_{1 \leq i \leq 4}\mathbb{P}(A_3 | B_i)\mathbb{P}(B_i) = \frac{a(a+c)(a+2c)}{(a+b)(a+b+c)(a+b+2c)} + \frac{ba(a+c)}{(a+b)(a+b+c)(a+b+2c)}$$
$$+ \frac{ab(a+c)}{(a+b)(a+b+c)(a+b+2c)} + \frac{b(b+c)a}{(a+b)(a+b+c)(a+b+2c)} = \frac{a}{a+b}$$
$\blacksquare$

### Teorema de Bayes

A definição de probabilidade condicional e da regra do produto levam a um resultado muito importante da teoria das probabilidades: o teorema de Bayes. Seja $(\Omega,\mathcal{F},\mathbb{P})$ um espaço de probabilidades e $A_1,...,A_n$ uma partição de $\Omega$. Nessa condições, tem-se:

$$\mathbb{P}(A_i \ | \ B) = \frac{\mathbb{P}(B | A_i) \mathbb{P}(A_i)}{\mathbb{P}(B)} = \frac{\mathbb{P}(B | A_i) \mathbb{P}(A_i)}{\sum_j\mathbb{P}(B|A_j)\mathbb{P}(A_j)}$$

### Exemplo

Considere o espaço amostral $\Omega = \{(x,y) : x \in \{0,...,5\}, y \in \{0,1,2\}\}$.

Vamos ilustrar uma aplicação do teorema de Bayes tomando a partição formada pelos conjuntos $A_i$ e o conjunto $B$, ambos definidos abaixo:

$$A_i : \text{A urna contém exatamente }i\text{ bolas brancas.}$$
$$B : \text{Observação de 1 bola branca.} $$

Nessas condições, tem-se:

$$ \mathbb{P}(B \ | \ A_i) = \frac{{i \choose 1}{5-i \choose 1}}{5 \choose 2}$$

Assumindo que $\mathbb{P}(A_i) = \frac{1}{6}, i = 0,...,5$, teremos:

$$ \mathbb{P}(A_j \ | \ B) = \frac{j(5-j)}{\sum_{i=0}^5i(5-i)}$$

$\blacksquare$

### Exemplo

Imagine que a equipe de buscas de um avião caído dividiu as proximidades do acidente em três regiões. Os investigadores acreditam que a queda do avião em duas dessas regiões é igualmente provável, com probabilidade $\frac{1}{4}$. Os investigadores, após não encontrar nada na terceira região, desejam calcular a probabilidade dessa busca ter resultado em um falso negativo. Eles consideram que $\mathbb{P}(B \ | \ A_3) = \alpha$ e $\mathbb{P}(B|A_i) = 1, i = 1,2$. Pelo teorema de Bayes, a probabilidade do avião ter caído na terceira região, dado que a busca não resultou em nada é dada por:

$$\frac{\frac{1}{2}\alpha}{\frac{1}{4}+\frac{1}{4}+\frac{\alpha}{2}} = \frac{\alpha}{1+\alpha}$$

## Independência

Dois eventos $A,B \in \mathcal{F}$ são independentes se $\mathbb{P}(A \ | \ B) = \mathbb{P}(A)$

Dessa definição decorre que a proposição "$A$ é independente de $B$" é equivalente a qualquer uma das proposições a seguir:

1. $A$ é independente de $B^c$
2. $A^c$ é independente de $B$
3. $A^c$ é independente de $B^c$ 

Três ou mais eventos também podem ser independentes, mas para que isso ocorra é necessária a ocorrência de várias identidades. $A_1,...,A_n$ serão CONJUNTAMENTE independentes se $\forall E \subset \{1,...,n\}$ com mais do que dois elementos for verdade que $\mathbb{P}\left(\bigcap_{j \in E} A_j\right) = \prod_{j \in E}\mathbb{P}(A_j)$
