```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aula 8 

### Vetores aleatórios

Um vetor aleatório é uma variável aleatória que mapeia os elementos de $\Omega$ em $\mathbb{R}^k$, k > 1. 
Análogo ao caso em que $k=1$, vetores aleatórios possuem funções de distribuição de probabilidades, mas essas funções são multivariadas.

Cada uma das entradas de um vetor aleatório também é uma variável aleatória em um espaço de probabilidades conveniente. Seja $k$ a dimensão do espaço em que um vetor aleatório está definido. As distribuições marginais das entradas $X_1,...,X_k$ de $X$ é dada por:

$$F_{X_i}(x_i) = \lim_{t \rightarrow \infty} F_X(t,t,...,x_i, t,...t)$$

### Vetores aleatórios discretos

Dizemos que um vetor aleatório $X$ é discreto se existe $A$ finito ou enumrável $A \in \mathcal{B}(\mathbb{R}^k)$ tal que $\mathbb{P}(A) = 1$. Isto é, $A = \{x_1,x_2,...\}$

$$\mathbb{P}_X(A)=\sum_{i=1}^\infty\mathbb{P}_X(\{x_n\})=1$$
À função $f:A\rightarrow\mathbb{R}_+$ que associa a cada $x \in A$ $\mathbb{P}_X(\{x\})=p_x$ damos o nome de função (densidade) de probabilidade da v.a. $X$.

#### Principais modelos discretos

1. Uniforme (Notação: $X \sim U(x_1,...,x_k)$)

Dizemos que a v.a. $X$ tem distribuição (ou lei) uniforme em $\{x_1,...,x_k\}$ se $\mathbb{P}(X=x) = \frac{1}{k}\mathbb{I}(x)_{\{x_1,...,x_k\}}$

2. Bernoulli (Notação: $X \sim Ber(p)$)

Dizemos que a v.a. $X$ tem distribuição Bernoulli de parâmetro $p$ se

$$\mathbb{P}(X = x) = p^x(1-p)^{1-x}\mathbb{I}(x)_{\{0,1\}}$$
3. Binomial (Notação: $X \sim Bin(n,p)$)

Dizemos que a v.a. $X$ tem distribuição (ou lei) binomial com parâmetros $n$ e $p$ se

$$\mathbb{P}(X = x) = {n \choose x}p^x(1-p)^{n-x}\mathbb{I}(x)_{\{0,...,n\}}$$

4. Geométrico (Notação: $X \sim Geom(p)$)

Dizemos que a v.a. $X$ tem distribuição (ou lei) geométrica com parâmetro $p$ se

$$\mathbb{P}(X = x) = p(1-p)^{x-1}\mathbb{I}(x)_{\{1,2,...\}}$$

5. Poisson (Notação: $X \sim Poi(\lambda)$)

Dizemos que a v.a. $X$ tem distribuição (ou lei) de Poisson com parâmetro $\lambda$ se

$$\mathbb{P}(X = x) = \frac{e^{-\lambda}\lambda^x}{x!}\mathbb{I}(x)_{\{0,1,2,...\}}$$

6. Hipergeométrico (Notação: $X \sim HG(n_1,n_2,N)$)

Dizemos que a v.a. $X$ tem distribuição (ou lei) hipergeométrica de parâmetros $n_1, n_2$ e $n$ se

$$\mathbb{P}(X = x) = \frac{{n_1 \choose x}{n_2 \choose n - x}}{{n_1 + n_2 \choose n}}\mathbb{I}(x)_{?,...,\min(n_1,n)}$$
7. Hipergeométrico Multivariada (Notação: $X \sim HGM(n_1,n_2,...,n_{k+1},N)$)

$$\mathbb{P}(X = (x_1,...,x_k)) = \frac{{n_1 \choose x_1}{n_2 \choose x_2}...{n_k \choose x_k}{n_{k+1} \choose n - \sum_{i=1}^{k}x_i}}{{n_1 + n_2 + ... + n_k \choose n}}\prod_{i=1}^{k}\mathbb{I}(x_i)_{?,...,\min(n_i,n)}$$
8. Multinomial (Notação: $X \sim Mult(n,p_1,...,p_k,p_{k+1})$)

$$\mathbb{P}(X = (x_1,...,x_k)) = {n \choose x_1,...,x_k}p_1^{x_1}...p_k^{x_k}p_{k+1}^{x_{k+1}}$$

$$\sum_{i=1}^k p_i < 1, p_i > 0$$
$$\sum_{j=1}^k x_i = n-x_{k+1}$$

### Vetores aleatórios contínuos

$X:\Omega \rightarrow \mathbb{R}^k$ é um v.a. contínuo se $F_X$ é contínua. Essa definição apoia-se na definição de continuidade usual, analogamente definimos um vetor aleatório $X$ como absolutamente contínuo se existe $f_X:\mathbb{R}^k \rightarrow \mathbb{R}_+$ contínua tal que

$$F_X(t_1,...,t_k) = \int_{-\infty}^{t_1}...\int_{-\infty}^{t_k}f_X(x_1,...,x_k)dx_1...dx_k$$

Nesse caso chamamos $f_{X}$ de função densidade de probabilidade de $X$.

Dizemos que a v.a. $X$ é singular se $F_X$ é contínua e $F_X^{'}(t) = 0, \ \forall t \in \mathbb{R}$ onde $F_x$ é diferenciável.
