```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lista 1

## Exercício 1

### a)

Seja $A = \bigcup_{n=1}^{\infty} \left(a, b - \frac{1}{n}\right]$. Primeiro vamos mostrar que $(a,b) = A$. Isso será feito provando duas proposições:

1. $b - \epsilon \in A, \ \forall 0 < \epsilon \leq 1$

2. $A \subset (a,b)$

Para verificar que as duas proposições garantem o resultado, note que (1.) é equivalente a $[b-1,b)$ e, pela definição de $A$, também é verdade que $(a, b-1) \subset A$, o que resulta em $(a,b-1] \cup (b-1,b) =(a,b) \subset A$. Como $(a,b) \subset A$ e $A \subset (a,b)$, tem-se $A = (a,b)$

Seja $A_n = \left(a, b - \frac{1}{n}\right]$. A primeira proposição é verdadeira, pois para todo $0 < \epsilon < 1$ existe um $n^* \geq 1$ tal que $\frac{1}{n^*} < \epsilon$. Isso implica que para todo $\epsilon$ existe um $n^* \geq 1$ tal que $b - \epsilon < b - \frac{1}{n^*}$ ou, em outras palavras, que existe um $A_{n^*}$ tal que $b-\epsilon \in A_{n^*}$. Como $A_{n^*} \subset A$, a proposição 1. está demonstrada.

Para demonstrar a segunda proposição, basta notar duas coisas: 

1. Se $x \leq a$, então $x \notin A_n, \ \forall n \geq 1$, pois $x < \inf A_n = a$. Consequentemente $x \notin A$.
2. Se $x \geq b$, então $x \notin A_n, \ \forall n \geq 1$, pois $x > \sup A_n = \max A_n = b-\frac{1}{n}, \ \forall n \geq 1$. Consequentemente $x \notin A$.

Essas duas proposições juntas garantem que $x \in A \implies x > a \text{ e } x < b$. Equivalentemente $A \subset (a,b)$. 

Isso conclui a demonstração de $A = (a,b)$. Agora vamos mostrar que $B = \bigcup_{n=1}^{\infty} \left[a + \frac{1}{n},b\right) = (a,b)$ e a demonstração será muito parecida. Novamente vamos usar duas proposições e elas serão análogas as utilizadas na demonstração anterior:

1. $a + \epsilon \in A, \ \forall \ 0 < \epsilon \leq 1$
2. $B \subset (a,b)$

Para verificar que as duas proposições garantem o resultado, note que (1.) é equivalente a $(a,a+1]$ e, pela definição de $B$, também é verdade que $(a+1, b) \subset B$, o que resulta em $(a,a+1] \cup (a+1,b) =(a,b) \subset B$. Como $(a,b) \subset B$ e $B \subset (a,b)$ (proposição 2.), tem-se $B = (a,b)$.

Seja $B_n = \left[a + \frac{1}{n}, b\right)$. A primeira proposição é verdadeira, pois para todo $0 < \epsilon < 1$ existe um $n^* \geq 1$ tal que $\frac{1}{n^*} < \epsilon$. Isso implica que para todo $\epsilon$ existe um $n^* \geq 1$ tal que $a + \epsilon > a + \frac{1}{n^*}$ ou, em outras palavras, que existe um $B_{n^*}$ tal que $a+\epsilon \in B_{n^*}$. Como $B_{n^*} \subset B$, a proposição 1. está demonstrada.

Para demonstrar a segunda proposição, basta notar duas coisas: 

1. Se $x \leq a$, então $x \notin B_n, \ \forall n \geq 1$, pois $x < \min B_n = a + \frac{1}{n}$. Consequentemente $x \notin B$.
2. Se $x \geq b$, então $x \notin B_n, \ \forall n \geq 1$, pois $x \geq \sup B_n = b, \ \forall n \geq 1$ e $b \notin B_n, \ \forall \ n\geq 1$. Consequentemente $x \notin B$.

Essas duas proposições juntas garantem que $x \in B \implies x > a \text{ e } x < b$. Equivalentemente $B \subset (a,b)$. 

### b) 

Seja $A = \bigcap_{n=1}^{\infty} \left(a, b + \frac{1}{n}\right)$. Queremos mostrar que $(a,b] = A$. Isso será feito provando duas proposições:

1. $x > b \text{ ou }x \leq a \implies x \notin A$

2. $(a,b] \subset A$

Para verificar que as duas proposições garantem o resultado, note que (1.) é equivalente a $x \in A \implies x \in (a,b]$ (ou $A \subset (a,b]$. Como $A \subset (a,b]$ e $(a,b] \subset A$ (proposição 2.), tem-se $A = (a,b]$.

Seja $A_n = \left(a, b + \frac{1}{n}\right)$. A primeira proposição é verdadeira, pois para todo $0 < \epsilon < 1$ existe um $n^* \geq 1$ tal que $\frac{1}{n^*} < \epsilon$. Isso implica que para todo $\epsilon$ existe um $n^* \geq 1$ tal que $b + \frac{1}{n^*} < b + \epsilon$ ou, em outras palavras, que existe um $A_{n^*}$ tal que $b+\epsilon \notin A_{n^*}$. Como $A \subset A_{n^*}$, a proposição 1. está demonstrada.

Para demonstrar a segunda proposição basta notar que $(a,b] \subset A_n, \ \forall \ n \geq 1$.

### Exercício 2

Pelas definições usuais $\bar{A} = \lim \sup A_i = \cap_{i=1}^\infty \cup_{k=i}^{\infty} A_k$ e $A = \lim \inf \cup_{i=1}^\infty \cap_{k=i}^\infty A_k$. A demonstração de que $\bar{A}$ e $A$ são elementos de $\mathcal{F}$ pode ser feita em dois passos:

1. Como $A_i \in \mathcal{F}, \ \forall \ i \geq 1$, tem-se que interssecções infinitas e uniões infinitas de conjuntos $A_i$ também pertencem à $\mathcal{F}$. Dessa forma, os conjuntos $B_i \cup_{k=i}^\infty A_i$ e $C_i = \cap_{k=i}^\infty A_i$ percentem à $\mathcal{F}$ para todo $i \geq 1$.
2. Como $B_i, C_i \in \mathcal{F}, \ \forall \ i \geq 1$, tem-se que interssecções infinitas e uniões infinitas de conPajuntos $B_i$ (ou $C_i$) também pertencem à $\mathcal{F}$. Como os conjuntos $\bar{A}$ e $A$ podem ser descritos como uniões e intersecções inifitas de $B_i$'s e $C_i$'s (respectivamente), então $\bar{A} \in \mathcal{F}$ e $A \in \mathcal{F}$.

A parta da demonstração que compete $\lim_n A_n$ já está demonstrada, pois esse conjunto é definido apenas no caso em que $\bar{A} = A$. Quando essa igualdade valer, pela demonstração anterior é evidente que $\lim_n A_n \in \mathcal{F}$.

### Exercício 3

Seja $\{A_i\}_{i \geq 1}$ uma sequência tal que $A_{2n} = B$ e $A_{2n-1} = A$. Nessas considções, tem-se que

$$\lim \inf A_n = \bigcup_{i=1}^\infty \bigcap_{k=i}^\infty A_k = (B \cap A \cap B \cap ...) \cup (B \cap A \cap B ...)\cup... = A \cap B$$

$$\lim \sup A_n = \bigcap_{i=1}^\infty \bigcup_{k=i}^\infty A_k = (B \cup A \cup B \cup ...) \cap (B \cup A \cup B ...)\cap... = A \cup B$$

## Exercício 4

Primeiramente note que $A_n$ e $B_n$ são intervalos abertos na reta, então para mostrar que $I_1 = (a_1, b_1) \subset I_2 = (a_2, b_2)$ basta mostrar que $a_2 < a_1$ e $b_1 < b_2$ (e vice-versa). 

Para mostrar que $A_n$ é não decrescente, vamos mostrar que $A_n$ é crescente (portanto não decrescente):

$$\frac{1}{n+1} < \frac{1}{n} \implies -5 + \frac{1}{n+1} < -5 + \frac{1}{n}$$
$$\frac{1}{n+1} < \frac{1}{n} \implies -\frac{1}{n+1} > -\frac{1}{n}\implies 20 - \frac{1}{n} < 20 - \frac{1}{n+1}$$

Pelo que foi dito na primeira linha desta resolução e fazendo $a_1 = -5 + \frac{1}{n+1}$, $a_2 = -5 + \frac{1}{n+1}$, $b_1 = 20 - \frac{1}{n}$, $b_2 = 20 - \frac{1}{n+1}$ as proposições acima implicam que:

$$\left(-5 + \frac{1}{n}, 20 - \frac{1}{n}\right) \subset \left(-5 + \frac{1}{n+1}, 20 - \frac{1}{n+1}\right) \implies A_n \subset A_{n+1}.$$

Isso conclui a demonstração de que $A_n$ é crescente.

Para mostrar que $B_n$ é não crescente, vamos mostrar que $B_n$ é decrescente (portanto não crescente):

$$\frac{3}{n+1} < \frac{3}{n} \implies 7 + \frac{3}{n+1} < 7 + \frac{3}{n}$$

Pelo que foi dito na primeira linha desta resolução e fazendo $a_1 = a_2 = 0$, $b_1 = 7 + \frac{3}{n}$, $b_2 = 7 + \frac{3}{n+1}$ a proposição acima implica que:

$$\left(0, 7 + \frac{3}{n+1}\right) \subset \left(0, 7 + \frac{3}{n}\right) \implies B_{n+1} \subset B_n$$

Para obter os limites das sequências, basta notar que, nos casos em que as sequências são monótonas, os limites são definidos como as uniões infinitas (caso não decrescente) ou intersecções infinitas (caso não crescente) dos conjuntos.

Dessa forma, temos que $\cap_n^\infty B_n = (0,7)$, pois para todo $7 + \epsilon, \epsilon > 0$ existirá um $B_n$ que não contém esse número, mas o intervalo $(0,7)$ está contido em todos os $B_n$. Para o limite de $A_n$, temos que que $\cup_n^\infty A_n = (-5,20)$, pois todos os números $-5 + \epsilon$ e $20 - \epsilon$, $0 < \epsilon < 1$, percentem a algum conjunto $A_n$.

## Exercício 5

Generalizando o que foi discutido no exercício anterior, podemos dizer que um intervalo no $\mathbb{R}^2$ é um conjunto formado pelo produto cartesiano de dois intervalos na reta. Com essa definição, o critério de inclusão de dois intervalos da reta pode ser generalizado da seguinte forma: $I_1 = (x^-_1,x^+_1)\times(y_1^-,y^+_1) \subset I_2 = (x^-_2,x^+_2)\times(y_2^-,y^+_2)$ se $x^-_2 <= x^-_1$ e $x^+_1 <= x^+_2$ e $y^-_2 <= y^-_1$ e $y^+_1 <= y^+_2$, onde em pelo menos em uma dessas desigualdades vale a desigualdade estrita.

Usando essa ideia, podemos mostrar que $A_n$ é uma sequência crescente. Para isso, tome $x_n^- = 3 + 1/n$, $x_n^+ = 6 - 2/n$, $y_n^- = 0$, $y_n^+ = 2 - 1/n^2$ e note que

$$x_{n+1}^- < x_{n}^-, \ \forall \ n \geq 1$$
$$x_{n}^+ < x_{n+1}^+, \ \forall \ n \geq 1$$
$$y_{n+1}^- = y_{n}^-, \ \forall \ n \geq 1$$
$$y_{n}^+ < y_{n+1}^+, \ \forall \ n \geq 1$$
Com isso, temos que

$$A_n = (x_n^-, x_{n}^+)\times(y_n^-, y_{n}^+) \subset A_{n+1} = (x_{n+1}^-, x_{n+1}^+)\times(y_{n+1}^-, y_{n+1}^+), \ \forall \ n \geq 1$$
Como em $A_n$ é possível encontrar pontos com cordenadas tão próximas dos limites das sequências $x$ e $y$ quanto se queira, vale que o limite de $A$ é o conjunto $(3,6)\times(0,2)$.

Para obter o limite da sequência $B_n$, note que $B_{n+1} \subset B_n$, pois $B_{n+1}$ é uma bola de raio menor do que o raio da bola $B_n$ e as duas tem o mesmo centro. Por isso, essa sequência de bolas é decrescente e o seu limite pode ser obtido tomando a intersecção de todos os elementos da sequência, que corresponde ao centro das bolas, o ponto $(0,0)$.

## Exercício 6

### a)

$$\lim \sup A_n = \bigcap_i \bigcup_{k \geq i} \{(-1)^k\} = \{-1,1\}$$
$$\lim \inf A_n = \bigcup_i \bigcap_{k \geq i} \{(-1)^k\} = \emptyset$$
### b)

$$\lim \sup A_n = \bigcap_i \bigcup_{k \geq i} A_n = \mathbb{R}$$
$$\lim \inf A_n = \bigcup_i \bigcap_{k \geq i} A_n = \{0\} $$
### c)

Essa resolução vai partir da *intuição* de que o limite desta sequência é a bola aberta centrada em $(0,0)$ e com raio $1$, denotada $B_1(0)$. Com isso em mente, vamos de fato provar as seguintes proposições:

1. $\ p \in B_1(0) \implies p \in \lim \sup A_n$
2. $\ p \in B_1(0) \implies p \in \lim \inf A_n$
3. $\ p \notin B_1(0) \implies p \notin \lim \sup A_n$
4. $\ p \notin B_1(0) \implies p \notin \lim \inf A_n$

Embora alguns pares de proposições possam ser agrupados em frases mais simples (como por exemplo a união de 3. e 1. significar $\lim \sup A_n = B_1(0)$), não simplificaremos as expressões em prol da clareza da resolução. 

Nas demonstrações das proposições 1 a 4 vamos nos aproveitar de duas interpretações especiais dos conjuntos $\lim \sup A_n$ e $\lim \in A_n$. Pela fórmula $\lim \sup A_n = \cap_i \cup_{k \geq i} A_k$ podemos identificar que esse conjunto é composto por todos os elementos que pertencem a união de todos os $A_i$ a menos de um conjunto finito de $A_i$. Lendo essa frase de outra forma (uma forma muito mais simples, na verdade), percebe-se que o $\lim \sup A_n$ consiste no conjunto de todos os elementos que aparecem em infitos $A_i$'s. Interpretando $\lim \inf A_n = \cup_i \cap_{k \geq i} A_k$ analogamente, identifica-se que esse conjunto é formado por todos os elementos que pertencem a todos os $A_i$ a partir de um certo índice específico.    

Essas interpretações permitem reescrever as proposições 1-4 de maneira mais simples e que facilitarão a sua demonstração.

1. $\ p \in B_1(0) \implies p \text{ pertence a infinitos }A_n$
2. $\ p \in B_1(0) \implies p \text{ está em todos }A_n\text{ a partir de um certo }n^*$
3. $\ p \notin B_1(0) \implies p \text{ pertence apenas a um número finito de }A_n$
4. $\ p \notin B_1(0) \implies \text{ existem infitos }A_n\text{ tal que }p\text{ não pertence a }A_n$

A demonstração de 1. pode ser feita da seguinte forma:

Primeiro note que $p \in B_1(0) \implies p_1^2 + p_2^2 = \epsilon, \ \epsilon \in (0,1)$ e que os pontos de $A_{2n-1}, n \geq 1$ satisfazem

$$ x^2 + \frac{x}{2n-1} + \frac{1}{(2n-1)^2} + y^2 \leq 1, \ x,y \in \mathbb{R}^2.$$
Para concluir a demonstração, perceba que $\frac{1}{2n-1} + \frac{1}{(2n-1)^2}$ é uma sequência convergente a $0$ e portanto para $n > n_\gamma$ tem-se $\frac{p_1}{2n-1} + \frac{1}{(2n-1)^2} < \gamma, \ \forall \gamma \in (0,1)$. Dessa forma, basta tomar $n > n_{1-\epsilon}$, que é possível já que $\epsilon \in (0,1)$, para que $\frac{1}{2n-1} + \frac{1}{(2n-1)^2} < 1-\epsilon$ e dessa forma a inequação

$$p_1^2 + \frac{p_1}{2n-1} + \frac{1}{(2n-1)^2} + p_2^2 = \epsilon + \frac{1}{2n-1} + \frac{1}{(2n-1)^2} \leq 1-\epsilon + \epsilon = 1$$
será verdadeira. Concluindo: todo ponto da bola aberta $B_1(0)$ percente a todos os $A_n$ de índice ímpar a partir de um certo $2n_\gamma-1$ e a proposião 1. está demonstrada.

A demonstração de 2. pode ser feita da seguinte forma:

Novamente vamos usar que $p \in B_1(0) \implies p_1^2 + p_2^2 = \epsilon, \ \epsilon \in (0,1)$, mas dessa vez também vamos olhar pros $A_k$ com índice par (denotados $A_{2n}, n \geq 1$), pois precisamos garantir que $p$ pertence a todos esses conjuntos a partir de um certo índice. Os elementos de $A_{2n}$ satisfazem 

$$ x^2 + \frac{1}{(2n)^2} - \frac{x}{2n} + y^2 \leq 1, \ x,y \in \mathbb{R}^2.$$

Analisando essa desigualdade para $x = p_1$ e $y = p_2$ teremos

$$p_1^2 + \frac{1}{4n^2}-\frac{p_1}{2n} + p_2^2 \leq \epsilon + \frac{1}{4n^2}+\frac{|p_1|}{2n}.$$
Portanto, para concluir a demonstração outra vez vamos procurar um majorante para uma sequência convergente a 0: para todo $n > n_\gamma, \ \gamma \in (0,1)$ tem-se $\frac{1}{4n^2}+\frac{|p_1|}{2n} < \gamma$. Tomando $\gamma = 1-\epsilon$ a última inequação fica:

$$p_1^2 + \frac{1}{4n^2}-\frac{p_1}{2n} + p_2^2 \leq \epsilon + \frac{1}{4n^2}+\frac{|p_1|}{2n} \leq \epsilon + \gamma \leq 1.$$
Por conta da última argumentação, temos que todos os pontos da bola aberta de raio 1 pertencem a todos os $A_n$ de índice ímpar a partir de um certo índice, mas pela demonstração anterior também sabemos  que todos os pontos da bola aberta de raio 1 percentem a todos os $A_n$ de índice par a partir de um certo índice. Isso significa que existe um índice tal que todos os pontos da bola aberta de raio 1 percentem a todos os $A_n$.

Para finalizar a resolução, vamos demonstrar apenas a proposição 3, que já garante a proposição 4. Tome $p$ tal que $p_1^2 + p_2^2 = c \geq 1$. Então tem-se que $p$ não pertence a nenhum $A_n$ de índice ímpar, pois 

$$p_1^2 + \frac{p_1}{2n-1} + \frac{1}{(2n-1)^2} + p_2^2 \geq p_1^2 + p_2^2 - \frac{|p_1|}{2n-1} \geq c - \frac{|p_1|}{2n-1}.$$

Como $-\frac{|p_1|}{2n-1}$ converge a 0 pela esquerda, existe um $n > n_\gamma, \ \gamma \in (0,1)$ tal que $-\frac{|p_1|}{2n-1} > \gamma$. Tomando $\gamma = \frac{1-c}{2}$ teremos:

$$p_1^2 + \frac{p_1}{2n-1} + \frac{1}{(2n-1)^2} + p_2^2 \geq p_1^2 + p_2^2 - \frac{|p_1|}{2n-1} \geq c - \frac{|p_1|}{2n-1} \geq \frac{2c  + 1 - c}{2} = \frac{c+1}{2} > 1.$$
Em outros termos, toda vez que $n$ for maior do que o $n_\gamma$ supracitado teremos que a $p$ não percente a $A_n$ de índice ímpar. Como essa mesma demonstração também vale para os $A_n$ de índice par, a resolução está concluída.

## Exercício 7

### a)

Primeiro note que

$$\mathbb{P}\left(\bigcap_{i=1}^n A_i\right) = \mathbb{P}\left(\left(\bigcup_{i=1}^n A_i^c\right)^c\right) = 1-\mathbb{P}\left(\bigcup_{i=1}^n A_i^c\right).$$
 Agora, como $\mathbb{P}\left(\bigcup_{i=1}^n A_i^c\right) \leq \sum_{i=1}^n \mathbb{P}(A_i^c)$, tem-se $-\mathbb{P}\left(\bigcup_{i=1}^n A_i^c\right) \geq -\sum_{i=1}^n \mathbb{P}(A_i^c)$ e consequentemente:


$$\mathbb{P}\left(\bigcap_{i=1}^n A_i\right) = \mathbb{P}\left(\left(\bigcup_{i=1}^n A_i^c\right)^c\right) = 1-\mathbb{P}\left(\bigcup_{i=1}^n A_i^c\right) \geq 1 - \sum_{i=1}^n\mathbb{P}(A_i^c)$$
### b) 

Primeiro note que $\mathbb{P}(A_k) \geq 1-\epsilon \implies 1-\mathbb{P}(A_k^c) \geq 1-\epsilon \implies -\mathbb{P}(A_k^c) \geq -\epsilon$. Por conta disso a última inequação do item anterior pode ser reescrita da seguinte forma:

$$\mathbb{P}\left(\bigcap_{i=1}^n A_i\right) = \mathbb{P}\left(\left(\bigcup_{i=1}^n A_i^c\right)^c\right) = 1-\mathbb{P}\left(\bigcup_{i=1}^n A_i^c\right) \geq 1 - \sum_{i=1}^n\mathbb{P}(A_i^c) \geq 1 - \sum_{i=1}^n \epsilon = 1-n\epsilon$$

### c)

Primeiro note que

$$\mathbb{P}\left(\bigcap_{i=1}^\infty A_i\right) = \mathbb{P}\left(\left(\bigcup_{i=1}^\infty A_i^c\right)^c\right) = 1-\mathbb{P}\left(\bigcup_{i=1}^\infty A_i^c\right).$$

Agora, como pela $\sigma$-aditividade de $\mathbb{P}$ tem-se que $\mathbb{P}\left(\bigcup_{i=1}^\infty A_i^c\right) \leq \sum_{i=1}^\infty \mathbb{P}(A_i^c)$, tem-se $-\mathbb{P}\left(\bigcup_{i=1}^\infty A_i^c\right) \geq -\sum_{i=1}^\infty \mathbb{P}(A_i^c)$ e consequentemente:

$$\mathbb{P}\left(\bigcap_{i=1}^\infty A_i\right) = \mathbb{P}\left(\left(\bigcup_{i=1}^\infty A_i^c\right)^c\right) = 1-\mathbb{P}\left(\bigcup_{i=1}^\infty A_i^c\right) \geq 1 - \sum_{i=1}^\infty\mathbb{P}(A_i^c)$$
## Exercício 8

### a) 

Pela $\sigma$-aditividade de $\mathbb{P}$ tem-se que $\mathbb{P}\left(\bigcup_{i=1}^\infty A_i\right) \leq \sum_{i=1}^\infty \mathbb{P}(A_i)$. Como $\mathbb{P}(A_i) = 0$ para todo $i$, é verdade que $\mathbb{P}\left(\bigcup_{i=1}^\infty A_i\right) \leq 0$. Como as medidas de probabilidade satisfazem $\mathbb{P}(A) \geq 0$, tem-se que $\mathbb{P}\left(\bigcup_{i=1}^\infty A_i\right) = 0$.

### b) 

Pela Lei de Moore e pela $\sigma$-aditividade $\mathbb{P}$ temos que $\mathbb{P}\left(\bigcap_{i=1}^\infty A_i\right) = 1-\mathbb{P}(\bigcup_i^\infty A_i^c) \geq 1 - \sum_{i=1}^\infty \mathbb{P}(A_i^c)$. Como $\mathbb{P}(A_i^c) = 1-\mathbb{P}(A_i) = 0$, a última inequação fica $\mathbb{P}\left(\bigcap_{i=1}^\infty A_i\right) = 1-\mathbb{P}(\bigcup_i^\infty A_i^c) \geq 1 - \sum_{i=1}^\infty \mathbb{P}(A_i^c) \geq 1$. 

## Exercício 9

Vamos começar provando que $\mathbb{P}(A_n \cup B_n) \rightarrow 1$. Essa proposição é verdadeira pois $1 \geq \mathbb{P}(A_n \cup B_n) \geq \mathbb{P}(A_n)$ e o limitante inferior dessa desiguldade converge à 1.

Agora, pelo princípio de inclusão e exclusão, tem-se que $\mathbb{P}(A_n \cap B_n) = \mathbb{P}(A_n) + \mathbb{P}(B_n) - \mathbb{P}(A_n \cup B_n)$. Tomando o limite dos dois lados tem-se que $\lim \mathbb{P}(A_n \cap B_n) = \lim \mathbb{P}(A_n) + \lim \mathbb{P}(B_n) - \lim \mathbb{P}(A_n \cup B_n) = 1 + p -1 = p$.

## Exercício 10

### a)

$\mathcal{A}$ é uma $\sigma$-álgebra com relação de subconjuntos de $\Omega$: o complementar de $\emptyset$ é $\Omega$, que pertence à $\mathcal{A}$. O complementar de $\{1\}$ é $\{2,3,4\}$,  que pertence à $\mathcal{A}$. O complementar de $\{2\}$ é $\{1,3,4\}$, que pertence à $\mathcal{A}$. A união de $\{1\}$ e $\{2\}$ é $\{1,2\}$, que pertence à $\mathcal{A}$. O complementar de $\{1,2\}$ é $\{3,4\}$, que pertence à $\mathcal{A}$. Não existem novos conjuntos que precisam de avaliação.

### b)

$\mathcal{B}$ não é uma $\sigma$-álgebra. $\{1\}$ e $\{2\}$ são elementos de $\mathcal{B}$, mas a sua união não é.

## Exercício 11

Quando $B_n$ é uma sequência não crescente de eventos sabemos que $\mathbb{P}(\lim B_n) = \lim \mathbb{P}(B_n)$. Por isso, o fato de $\sup_k A_i = \cup_{i \geq k} A_i$ ser uma sequência não crescente garante que $\mathbb{P}(\lim \sup_k A_i) = \lim \mathbb{P}(\sup_k A_i)$. Como $\mathbb{P}(A_i)$ é maior que $c$ para todo $i$, $\mathbb{P}(\sup_k A_i)$ também é ($\mathbb{P}(\bigcup_{i \geq k} A_i) \geq \mathbb{P}(A_k) \geq c$) e consequentemente $\lim \mathbb{P}(\sup_k A_i) \geq c$.

## Exercício 12

1. $\emptyset \text{ é enumerável} \implies \emptyset^c = \Omega \in \mathcal{F}$
2. $A \in \mathcal{F} \implies A \text{ é enumerável ou }A^c\text{ é enumerável} \implies (A^c)^c \text{ é enumerável ou }A^c\text{ é enumerável} \implies A^c \in \mathcal{F}$
3. Se $A_i \in \mathcal{F}, \ i \geq 1$, então ou todos esses conjuntos são enumeráveis ou existe pelo menos um $A_{i^*}$ não-enumerável com $A_{i^*}^c$ enumerável. Nesse último caso, $\cap A_i^c$ é enumerável pois é um subconjunto $A_{i^*}^c$, que é enumerável. No caso em que todos os $A_i$ são enumeráveis, é verdade que $\cup A_i$ é enumerável, pois existe uma coleção enumerável de funções bijetoras $f_i:A_i \rightarrow \mathbb{N}$ que dá origem à função $f(j-\text{ésimo elemento de }A_i) = f(a_{ij}) = (i, f_i(a_{ij}))$. Como $f$ é uma bijeção de $\cup A_i$ em $\mathbb{N}^2$, basta encontrar uma bijeção de $\mathbb{N}^2$ em $\mathbb{N}$ para concluir que $\cup A_i$ é enumerável. Isso pode ser feito com o mapeamento de $\mathbb{N}^2$ em $\mathbb{N}$ sendo $f(i,j) = 2^i(2f_i(a_{ji})+1)-1$.

## Exercício 13

1. $B \in \mathcal{F}_B$, pois $B = B \cap B$ e $B \in \mathcal{F}_{\Omega}$.
2. Se $C \in \mathcal{F}_B$, então $C^c \in \mathcal{F}_B$. Isso vale porque $C \in \mathcal{F}_B \implies \exists A \in \mathcal{F}_\Omega: C = A \cap B \implies A^c \cap B \in \mathcal{F}_B$.
3. $C_i \in \mathcal{F}_B, \ \forall i \geq 1 \implies \exists A_i \in \mathcal{F}_\Omega, \ i \geq 1: C_i = A_i \cap B \implies \cup A_i \in \mathcal{F}_\Omega \implies C = \cup A_i \cap B = \cup C_i \in \mathcal{F}_B$.

## Exercício 14

1. $\Omega \in \mathcal{F}_1$, pois $\mathbb{P}(\Omega) = 1$
2. Se $C \in \mathcal{F}_1$, então  $\mathbb{P}(C) = 1$ ou  $\mathbb{P}(C^c) = 1$, que é equivalente a $\mathbb{P}((C^c)^c) = 1$ ou  $\mathbb{P}(C^c) = 1$. Isso garante que $C^c \in \mathcal{F}_1$
3. Se $C_i \in \mathcal{F}_B, \ i \geq 1$, então, pelo exercício 8, $\mathbb{P}(\cup C_i) = 1$ ou $\mathbb{P}(\cap C_i^c) = 0$. Isso garante que $\cup C_i \in \mathcal{F}_1$.

## Exercício 15

1. $B \in \mathcal{F}_1$, pois $\mathbb{P}(B \cap B) = \mathbb{P}(B)$
2. Se $C \in \mathcal{F}_1$, então  $\mathbb{P}(C \cap B) = \mathbb{P}(B)$ ou  $\mathbb{P}(B^c\cup C^c) = \mathbb{P}(B)$, que é equivalente a $\mathbb{P}((C^c \cup B^c)^c) = \mathbb{P}(B)$ ou  $\mathbb{P}(B^c \cup C^c) = \mathbb{P}(B)$. Isso garante que $C^c \in \mathcal{F}_1$

## Exercício 16

### a)

$\sigma(C_1) = \{\emptyset,\{1,2,3,4,5,6\},\{1,2\},\{3,4,5,6\}\}$

### b)

$\sigma(C_2) = \{\emptyset,\{1,2,3,4,5,6\},\{1,2\},\{3,4,5,6\},\{1\},\{2\},\{1,3,4,5,6\},\{2,3,4,5,6\}\}$

### c)

$\sigma(C_3) = \{\emptyset,\{1,2,3,4,5,6\},\{1,2\},\{2,3,4,5,6\},\{2\},\{1\},\{3,4,5,6\},\{1,3,4,5,6\}\}$

## Exercício 17

$\sigma(A_1,...,A_n) = \{\emptyset,\Omega\} \cup \{A_i \cup A_j, i \neq j\} \cup \{A_i \cup A_j \cap A_k, n \geq i > j > k \geq 1\} \cup ... \{\Omega\cap A_i^c, \ i = 1,...,n\}$

## Exercício 18

Primeiramente note que $(-\infty,x] = \left(\bigcup_{n \geq 1} \left[-n,x+\frac{1}{n}\right)\right) \bigcup \left(\bigcap_{n \geq 1} \left[x-\frac{1}{n},x+\frac{1}{n}\right)\right)$. Portanto, é verdade que $\mathcal{C} \subset \sigma(\mathcal{D})$, e consequentemente $\sigma(\mathcal{C}) \subset \sigma(\mathcal{D})$.

Para concluir a demonstração, basta notar que $[x,y) = \left(\bigcap_n\left(-\infty,y+\frac{1}{n}\right]\right)\bigcap\left(\bigcap_n\left(-\infty,x+\frac{1}{n}\right]\right)^c$. Isso garante que $\mathcal{D} \subset \sigma(\mathcal{C})$, e consequentemente $\sigma(\mathcal{D}) \subset \sigma(\mathcal{C})$. Portanto tem-se que $\sigma(\mathcal{D}) = \sigma(\mathcal{C})$.

## Exercício 19

1. $\mathbb{P}(\Omega = \mathbb{N}) = 1$
2. $\mathbb{P}(A) \geq 0, \forall \ A \in \mathcal{F}$
3. $\mathbb{P}$ não é $\sigma$-aditiva. Tome $A_i = \{i\}, \ i \geq 1$. Então $\mathbb{P}(\bigcup A_i = \mathbb{N}) \neq \sum_{i=1}^\infty \mathbb{P}(A_i) = 0$

## Exercício 20

Seja $\Omega = \mathbb{R}$.

1. $\mathbb{P}(\Omega = \mathbb{R}) = 1$
2. $\mathbb{P}(A) \geq 0, \forall \ A \in \mathcal{F}$
3. $\mathbb{P}$ não é $\sigma$-aditiva. Tome $A_i = (-(i+1),-i]\cup[i,i+1), i \geq 1$. Então $\mathbb{P}(\bigcup A_i = \mathbb{R}) \neq \sum_{i=1}^\infty \mathbb{P}(A_i) = \infty$

## Exercício 21

1. $\mathbb{P}(\Omega) = \sum_{i=1}^\infty \alpha_i = 1$
2. $\mathbb{P}(A) = \sum_{i=1}^\infty \alpha_i\mathbb{P}_i(A) \geq 0, \forall \ A \in \mathcal{F}$, pois as $\mathbb{P}_i$ são medidas de probabilidade.
3. Seja $\{A_i\} \in \mathcal{F}$ uma coleção de eventos disjuntos. $\mathbb{P}\left(\bigcup A_j\right) = \sum_{i=1}^\infty \alpha_i\mathbb{P}_i\left(\bigcup A_j\right) = \sum_{i=1}^\infty \alpha_i \sum_{j=1}^\infty \mathbb{P}_i\left(A_j\right) = \sum_{i=1}^\infty \sum_{j=1}^\infty \alpha_i\mathbb{P}_i\left(A_j\right) = \sum_{j=1}^\infty \sum_{i=1}^\infty \alpha_i\mathbb{P}_i\left(A_j\right) = \sum_{j=1}^\infty \mathbb{P}(A_j)$

## Exercício 22 

Vamos começar provando a desigualdade para $\lim \inf A_n$. Primeiramente note que $\mathbb{P}\left(\bigcap_{k \geq n}A_k\right) \leq \mathbb{P}(A_n)$, de onde decorre que

$$\liminf_n\mathbb{P}\left(\bigcap_{k \geq n}A_k\right) \leq \liminf_n\mathbb{P}(A_n).$$
Mas, como $B_n = \bigcap_{k \geq n}A_k, \ n \geq 1$ é uma sequência não decrescente de eventos, tem-se que $\mathbb{P}(\bigcup_n B_n) = \mathbb{P}(\liminf A_n) = \lim \mathbb{P}(B_n) = \liminf\mathbb{P}(B_n)$. Considerando essa observação, a desigualdade anterior fica

$$\mathbb{P}(\liminf A_n) = \liminf_n\mathbb{P}\left(\bigcap_{k \geq n}A_k\right) \leq \liminf_n\mathbb{P}(A_n).$$
A prova para o $\limsup$ pode ser feita de maneira análoga: note que $\mathbb{P}\left(\bigcup_{k \geq n}A_k\right) \geq \mathbb{P}(A_n)$, de onde decorre que

$$\limsup_n\mathbb{P}\left(\bigcup_{k \geq n}A_k\right) \geq \limsup_n\mathbb{P}(A_n).$$
Mas, como $C_n = \bigcup_{k \geq n}A_k, \ n \geq 1$ é uma sequência não crescescente de eventos, tem-se que $\mathbb{P}(\bigcap_n C_n) = \mathbb{P}(\limsup A_n) = \lim \mathbb{P}(C_n) = \limsup\mathbb{P}(C_n)$. Considerando essa observação, a desigualdade anterior fica

$$\mathbb{P}(\limsup A_n) = \limsup_n\mathbb{P}\left(\bigcup_{k \geq n}A_k\right) \geq \limsup_n\mathbb{P}(A_n).$$
# Lista 2


## Exercico 1

Se os eventos $A_j$ são tais que $\sum_{i=1}^\infty \mathbb{P}(A_i) < \infty$, então a sequência $p_n = \sum_{i=n}^\infty \mathbb{P}(A_i)$ converge a $0$. Além disso, nesses termos é verdade que

$$p_n = \sum_{i=n}^\infty \mathbb{P}(A_i) \geq \mathbb{P}\left(\bigcup_{i \geq n} A_i\right).$$
Tomando o limite dos dois lados na desigualdade acima teremos que

$$0 = \lim_n p_n \geq \lim_n \mathbb{P}\left(\bigcup_{i \geq n}A_i\right) \geq 0$$
Como $\lim\mathbb{P}\left(\bigcup_{i \geq n}A_i\right) = \mathbb{P}(\limsup A_i)$, o resultado está demonstrado.

## Exercício 2

$$\mathbb{P}(A_j | A) = \frac{\mathbb{P}(A_j \cap A)}{\mathbb{P}(A)} = \frac{\mathbb{P}(A|A_j)\mathbb{P}(A_j)}{\mathbb{P}(A)} = \frac{j/15 \times (5-j)/15)}{\sum_{j=1}^5 (5-j)/15 \times j/15} = \frac{j (5-j)}{\sum_{i=1}^5 5j-j^2} = \frac{(5j-j)j}{75-55} = \frac{j(5-j)}{20}$$
## Exercício 3

$$\mathbb{P}(A|B) > \mathbb{P}(A) \implies \mathbb{P}(B|A)\frac{\mathbb{P}(A)}{\mathbb{P}(B)} > \mathbb{P}(A) \implies \frac{\mathbb{P}(B|A)}{\mathbb{P}(B)} > 1 $$

## Exercício 4

### i)

$$\mathbb{P}(A^c|B) = \frac{\mathbb{P}(A^c \cap B)}{\mathbb{P}(B)} = \frac{1-\mathbb{P}(A \cup B^c)}{\mathbb{P}(B)} = \frac{1-\mathbb{P}(A)-\mathbb{P}(B^c) + \mathbb{P}(A \cap B^c)}{\mathbb{P}(B)} = \frac{\mathbb{P}(B) - \mathbb{P}(A) + \mathbb{P}(A \cap B^c)}{\mathbb{P}(B)} = $$
$$\frac{\mathbb{P}(B)-\mathbb{P}(A) + \mathbb{P}(A \cap B^c) + \mathbb{P}(A \cap B) - \mathbb{P}(A \cap B)}{\mathbb{P}(B)} = 1-\mathbb{P}(A|B)$$

### ii)

$$\mathbb{P}(A \cup B | C) = \frac{\mathbb{P}((A \cup B) \cap C)}{\mathbb{P}(C)} = \frac{\mathbb{P}((A \cap C) \cup (B \cap C))}{\mathbb{P}(C)} = \frac{\mathbb{P}(A\cap C) + \mathbb{P}(B \cap C) - \mathbb{P}(A \cap C \cap B \cap C)}{\mathbb{P}(C)} = \mathbb{P}(A|C) + \mathbb{P}(B | C) - \mathbb{P}(A\cap B|C)$$

### iii)

Seja $\Omega = \{1,2,3,4}$, $B = \{1,2\}$ e $A = \{1\}$. Considere o espaço de probabilidade $(\Omega,\mathcal{P}(\Omega),\mathbb{P})$ em que $\mathbb{P}(\{i\}) = 1/4$. Tem-se $\mathbb{P}(A|B) = 1/2 \neq 1-\mathbb{P}(A|B^c) = 1$

### iv)

Essa notação está certa??

## Exercício 5

$$\mathbb{P}(B|U_j) = \min\{1,m_j/n_j\}, \ \mathbb{P}(U_j) = 1/3$$

$$\mathbb{P}(U_j|B) = \frac{\mathbb{P}(B|U_j)\mathbb{P}(U_j)}{\mathbb{P}(B)}=\frac{\min\{1,m_j/n_j\}}{\min\{1,m_1/n_1\}+\min\{1,m_2/n_2\}+\min\{1,m_3/n_3\}}$$
## Exercício 6

$$\mathbb{P}(U_k = p) = \frac{n}{m} +\mathbb{P}(U_{k-1} = p)\left(\frac{n+1}{m}-\frac{n}{m}\right) = \frac{n}{m}+\frac{\mathbb{P}(U_{k-1} = p)}{m}, \ \forall\ k\geq2$$

Além disso,

$$\mathbb{P}(U_1 = p) = \frac{n}{m}$$

Com isso, tem-se:

$$\mathbb{P}(U_2 = p) = \frac{nm+n}{m^2}$$

$$\mathbb{P}(U_3 = p) = \frac{nm^2+nm+n}{m^3}$$

E, por indução, teremos

$$\mathbb{P}(U_k = p) = \frac{n+\sum_{i=1}^{k-1} nm^i}{m^k}$$

## Exercício 7

## Exercício 8

### b)

Quando existem $n$ equações e $n$ frases, o problema pode ser resolvido considerando o espaço amostral $(P([n]),\mathcal{F},\mathbb{P})$ em que $P([n])$ representa o conjunto das permutações do conjunto $\{1,...,n\}$, $\mathcal{F}$ representa o conjunto das partes de $P([n])$ e $\mathbb{P}$ é a medida uniforme ($\mathbb{P}(\sigma) = 1/n!$). Primeiramente, defina os conjuntos $A_i = \text{ a }i-\text{ésima frase foi adivinhada corretamente}, i \geq 1$. Nesse contexto, o evento de interesse pode ser expresso como

$$\text{Probabilidade de pelo menos um paramento correto }=\bigcup_{i=1}^n A_i.$$
A probabilidade desse conjunto pode ser calculada utilizando o princípio da inclusão e exclusão:

$$\mathbb{P}\left(\bigcup_{i=1}^n A_i\right) = \sum_{\emptyset \neq I \subset \{1,...,n\}}(-1)^{|I|-1}\mathbb{P}\left(\bigcap_{i \in I}A_i\right).$$

A igualdade acima pode ser simplificada seguindo dois passos:

1. Calculando $\mathbb{P}\left(\bigcap_{i \in I}A_i\right)$. Como a medida em questão é uniforme, tem-se que

$$\mathbb{P}\left(\bigcap_{i \in I}A_i\right) = \frac{(n-|I|)!}{n!}$$

2. Notando que existem $n \choose k$ conjuntos $I \subset \{1,...,n\}$ tal que $|I| = k$

Com essas duas observações, a fórmula fica

$$\mathbb{P}\left(\bigcup_{i=1}^n A_i\right) = \sum_{\emptyset \neq I \subset \{1,...,n\}}(-1)^{|I|-1}\mathbb{P}\left(\bigcap_{i \in I}A_i\right) = \sum_{i=1}^n (-1)^{i-1} {n \choose i} \frac{(n-i)!}{n!} = \sum_{i=1}^n (-1)^{i-1} \frac{1}{i!}.$$

### a)

No exercício 1 do livro há 4 frases e 4 equações, portanto a probabilidade de acertar pelo menos uma delas é $1 - 1/2 + 1/6 - 1/24$.

### c)

Para todo $x \in \mathbb{R}$ a expansão de $e^x$ em série de potências é

$$e^x = \sum_{i=0}^\infty \frac{x^{i}}{i!}.$$
Dessa fórmula decorre que

$$e^{-1} = \sum_{i=0}^\infty \frac{(-1)^{i}}{i!} = 1-\sum_{i=1}^\infty\frac{(-1)^{i-1}}{i!} \implies 1-e^{-1} = \sum_{i=1}^\infty\frac{(-1)^{i-1}}{i!}.$$
Portanto

$$\mathbb{P}\left(\bigcup_{i=1}^n A_i\right) = \sum_{i=1}^\infty\frac{(-1)^{i-1}}{i!} = 1-e^{-1}.$$
## Exercício 9

### a)

$$\mathbb{P}(B|A_n) \geq c \implies \frac{\mathbb{P}(B \cap A_n)}{\mathbb{P}(A_n)} \geq c \implies \mathbb{P}(B \cap A_n) \geq c\mathbb{P}(A_n) \implies \sum_{i=1}^n \mathbb{P}(B \cap A_n) \geq c \sum_{i=1}^n \mathbb{P}(A_n) \implies \mathbb{P}(B \cap (\cup A_n)) \geq c\mathbb{P}(\cup A_n)$$
### b)

$$\mathbb{P}(B|A_n) = c \implies \frac{\mathbb{P}(B \cap A_n)}{\mathbb{P}(A_n)} = c \implies \mathbb{P}(B \cap A_n) = c\mathbb{P}(A_n) \implies \sum_{i=1}^n \mathbb{P}(B \cap A_n) = c \sum_{i=1}^n \mathbb{P}(A_n) \implies \mathbb{P}(B \cap (\cup A_n)) = c\mathbb{P}(\cup A_n)$$
### c)

$$\mathbb{P}(A_{n+1}|A_{n}) \leq \frac{1}{2} \implies \frac{\mathbb{P}(A_n \cap A_{n+1})}{\mathbb{P}(A_{n})} \leq \frac{1}{2} \implies \frac{\mathbb{P}(A_{n+1})}{\mathbb{P}(A_n)} \leq \frac{1}{2}$$
Disso decorre que:

$$\prod_{i=1}^n\frac{\mathbb{P}(A_{i+1})}{\mathbb{P}(A_i)} \leq \frac{1}{2^n} \implies \frac{\mathbb{P}(A_{n+1})}{\mathbb{P}(A_1)} \leq \frac{1}{2^n}$$

Como o limitante superior de $\mathbb{P}(A_{n+1})$ converge a $0$, a sequência também converge a $0$.

## Exercício 10

$$\mathbb{P}(\text{choverá amanhã}|\text{choveu hoje}) = 0.7$$
$$\mathbb{P}(\text{choverá amanhã}|\text{não choveu hoje}) = 0.4$$
$$\mathbb{P}(\text{choverá depois de amanhã}|\text{choveu hoje}) = \mathbb{P}(\text{choverá amanhã}|\text{choveu hoje})\mathbb{P}(\text{choverá depois de amanhã}|\text{choverá amanhã}) + $$
$$\mathbb{P}(\text{não choverá amanhã}|\text{choveu hoje})\mathbb{P}(\text{choverá depois de amanhã}|\text{não choverá amanhã}) =$$

$$ 0.7^2 + 0.3\times0.4$$
## Exercício 11

$$\mathbb{P}(\text{erra}|\text{sabe})=0$$
$$\mathbb{P}(\text{erra}|\text{não sabe})=1-\frac{1}{m}$$
$$\mathbb{P}(\text{sabe}|\text{não erra}) = \frac{\mathbb{P}(\text{não erra}|\text{sabe})\mathbb{P}(\text{sabe})}{\mathbb{P}(\text{não erra})} = \frac{p}{p + (1-p)\left(1-\frac{1}{m}\right)} = \frac{p}{1 + \frac{p-1}{m}} = \frac{mp}{m+p-1}$$

## Exercício 12

### a)

$$\mathbb{P}\left(\bigcap_{k=1}^n A_i^c\right) = \prod_{k=1}^n(1-p_i)$$
### b)

$$\mathbb{P}\left(\bigcup_{k=1}^n A_i\right) = \sum_{\emptyset \neq I \subset \{1,...,n\}}(-1)^{|I|-1}\mathbb{P}\left(\bigcap_{i \in I}A_i\right) = \sum_{\emptyset \neq I \subset \{1,...,n\}}(-1)^{|I|-1}\prod_{i \in I}p_i$$
### c)

$$\mathbb{P}\left(\bigcup_{j=1}^n\left(\left(\bigcap_{i \neq j} A_i^c\right)\bigcap A_j\right)\right) = \sum_{j=1}^n\mathbb{P}\left(\left(\bigcap_{i \neq j} A_i^c\right)\bigcap A_j\right) = \sum_{j=1}^n p_j \prod_{i \neq j}p_i$$
### d)

$$\mathbb{P}\left(\bigcup_{I \subset \{1,..,n\}, |I|=2}\left(\left(\bigcap_{i \notin I} A_i^c\right)\bigcap_{j \in I} A_j\right)\right) = \sum_{I \subset \{1,..,n\}, |I|=2}\mathbb{P}\left(\left(\bigcap_{i \notin I} A_i^c\right)\bigcap_{j \in I} A_j\right) = \sum_{I \subset \{1,..,n\}, |I|=2} \prod_{j \in I}p_j \prod_{i \notin I}p_i$$

### e)

$$\mathbb{P}\left(\bigcap_{i=1}^n A_i\right) = \prod_{i=1}^n p_i$$

### f)

$$\mathbb{P}\left(\bigcup_{I \subset \{1,..,n\}, |I|\leq n-1}\left(\left(\bigcap_{i \notin I} A_i^c\right)\bigcap_{j \in I} A_j\right)\right) = \sum_{I \subset \{1,..,n\}, |I|\leq n-1}\mathbb{P}\left(\left(\bigcap_{i \notin I} A_i^c\right)\bigcap_{j \in I} A_j\right) = \sum_{I \subset \{1,..,n\}, |I|\leq n-1} \prod_{j \in I}p_j \prod_{i \notin I}p_i$$
Existe uma solução mais simples:

$$1-\mathbb{P}\left(\bigcap_{i=1}^n A_i\right) = 1 - \prod_{i=1}^n p_i$$
## Exercício 13

### a)

$$\mathbb{P}(E|G) = \mathbb{P}(E) \text{ e }\mathbb{P}(E|F) = \mathbb{P}(E) \implies \mathbb{P}(E|F\cup G) = \frac{\mathbb{P}((E \cap F) \cup (E \cap G))}{\mathbb{P}(F \cup G)} = \frac{\mathbb{P}(E)\mathbb{P}(F) + \mathbb{P}(E)\mathbb{P}(G) - \mathbb{P}(E\cap F \cap G)}{\mathbb{P}(F \cup G)} = \frac{\mathbb{P}(E)\mathbb{P}(F) + \mathbb{P}(E)\mathbb{P}(G) - \mathbb{P}(E\cap F \cap G)}{\mathbb{P}(F)+\mathbb{P}(G) - \mathbb{P}(F\cap G)}$$

### b)

$$\mathbb{P}(E|G) = \mathbb{P}(E) \text{ e }\mathbb{P}(E|F) = \mathbb{P}(E) \implies \mathbb{P}(E|F\cup G) = \frac{\mathbb{P}((E \cap F) \cup (E \cap G))}{\mathbb{P}(F \cup G)} = \frac{\mathbb{P}(E)\mathbb{P}(F) + \mathbb{P}(E)\mathbb{P}(G) - \mathbb{P}(E\cap F \cap G)}{\mathbb{P}(F \cup G)} = \frac{\mathbb{P}(E)\mathbb{P}(F) + \mathbb{P}(E)\mathbb{P}(G) - \mathbb{P}(E\cap F \cap G)}{\mathbb{P}(F)+\mathbb{P}(G) - \mathbb{P}(F\cap G)} = \mathbb{P}(E)$$

### c)

$$\mathbb{P}(F|G) = \mathbb{P}(F) \text{ e }\mathbb{P}(E|F)=\mathbb{P}(E)\text{ e }\mathbb{P}(E|F \cap G) = \mathbb{P}(E) \implies \mathbb{P}(G|E \cap F) = \frac{\mathbb{P}(G \cap E \cap F)}{\mathbb{P}(E \cap F)} = \frac{\mathbb{P}(E)\mathbb{P}(F \cap G)}{\mathbb{P}(E)\mathbb{P}(F)} = \frac{\mathbb{P}(E)\mathbb{P}(F)\mathbb{P}(G)}{\mathbb{P}(E)\mathbb{P}(F)} = \mathbb{P}(G)$$
## Exercício 14

$$\mathbb{P}(E_n \cap F_n) = \mathbb{P}(E_n)\mathbb{P}(F_n), \forall \ n \geq 1$$
$$\mathbb{P}\left(\bigcup E_n \bigcap \bigcup F_n\right) = \mathbb{P}\left(\bigcup_{i=1}^{\infty} E_i\bigcap F_i\right) = \lim \mathbb{P}\left(\bigcup_{i=1}^n E_i \cap F_i\right) = \lim \mathbb{P}\left(E_n \cap F_n\right) = \lim \mathbb{P}(E_n) \lim \mathbb{P}(F_n) = \mathbb{P}(E)\mathbb{P}(F)$$

## Exercício 15

Considere o espaço de mensurável de infinitos lançamentos de moedas $(\Omega,\mathcal{F})$, onde $\mathcal{F}$ é a $\sigma$-álgebra gerada pelos conjuntos que dependem apenas de um número finito de lançamentos. Sendo $\omega$ um elemento de $\Omega$, defina $X_i(\omega) = \omega_i$ e $\mathbb{P}(X_i = 1) = a_i$, com todas as $X_i$ sendo independentes. Seja $\mathbb{P}$ a medida de probabilidade gerada pelas variáveis aleatórias $X_1, X_2, X_3,...$. Para demonstar o que se pede no enunciado do exercício vamos considerar os seguintes eventos:

$$ \mathbb{P}\left(\bigcap_{i=1}^\infty \{X_i = 0\}\right) = \prod_{i=1}^\infty(1-a_i) $$
$$ \mathbb{P}\left(\bigcup_{i=1}^\infty \{X_i = 1\}\right) = \mathbb{P}\left(\bigcup_{i=1}^\infty \left(\{X_i = 1\}\bigcap\bigcap_{j=1}^{i-1}\{X_j = 0 \}\right)\right) = \sum_{i=1}^\infty\left[a_i\prod_{j=1}^{i-1}(1-a_j)\right]$$

Em que as duas últimas desigualdades valem, respectivamente, pois:

1. $\omega \in \bigcup_{i=1}^\infty \{X_i = 1\} \iff \exists \ k : \omega \in  \{X_k = 1\}\bigcap\left(\bigcap_{j=1}^{k-1}\{X_j = 0\}\right)$. ($\Rightarrow$) Se $\omega \in \bigcup_{i=1}^\infty \{X_i = 1\}$, $I = \{i : w_i = 1\}$ é não vazio e consequentemente admite mínimo. Se $i^* = \min I$, então $\omega \in \{X_i^* = 1\}\bigcap\left(\bigcap_{j=1}^{i^*-1}\{X_j = 0\}\right)$ por construção. ($\Leftarrow$) Seja $k$ um índice tal que $\omega \in \{X_k = 1\}\bigcap\left(\bigcap_{j=1}^{k-1}\{X_j = 0\}\right)$. Então, como $\{X_k = 1\}$, $\omega \in \bigcup_{i=1}^\infty \{X_i = 1\}$.
2. $\{X_k = 1\}\bigcap\left(\bigcap_{j=1}^{k-1}\{X_j = 0\}\right)$ são disjuntos para todo $k$.

Como $\bigcap_{i=1}^\infty \{X_i = 0\} = \left(\bigcup_{i=1}^\infty \{X_i = 1\}\right)^c$, o resultado está demonstrado.

## Exercício 16

$$P_n = p + (1-2p)P_{n-1}, \ n \geq 1$$
$$P_0 = 1$$

1. Vale para $n = 1$. $P_1 = p + (1-2p) = 1-p = \frac{1+(1-2p)^1}{2}$
2. Se vale para $n$, vale para $n+1$:

$$P_{n+1} = p + (1-2p)\frac{1+(1-2p)^n}{2} = p + \frac{1-2p + (1-2p)^{n+1}}{2} = \frac{1 + (1-2p)^{n+1}}{2}$$

## Exercício 17

$$\mathbb{P}(U_{n+1} = U_1) = \alpha_n = \mathbb{P}(U_{n} = U_1)\mathbb{P}(U_{n+1} = U_1 | U_{n} = U_1) + (1-\mathbb{P}(U_n = U_1))\mathbb{P}(U_{n+1}=U_1|U_n = U_2) =$$
$$\mathbb{P}(U_n = U_1)(\mathbb{P}(U_{n+1} = U_1 | U_{n} = U_1) -\mathbb{P}(U_{n+1}=U_1|U_n = U_2)) + \mathbb{P}(U_{n+1}=U_1|U_n = U_2) = \alpha_n(p - (1-p')) + (1-p').$$

Vamos provar por indução que 

$$\alpha_{n} = \frac{1-p'}{2-p-p'} + \left(\alpha - \frac{1-p'}{2-p-p'}\right)(p + p' - 1)^{n-1}, n \geq 1$$
1. Vale para $n = 1$

$$\alpha_1 = \frac{1-p'}{2-p-p'} + (\alpha - \frac{1-p'}{2-p-p'})(p + p' -1)^0 = \alpha$$

2. Se vale para $n$ vale para $n+1$:

$$\alpha_{n+1} = \left(\frac{1-p'}{2-p-p'} + \left(\alpha - \frac{1-p'}{2-p-p'}\right)(p + p' - 1)^{n-1}\right)(p+p'-1)+1-p' = $$
$$\left(\frac{(1-p')(p+p'-1)}{2-p-p'} + \left(\alpha - \frac{1-p'}{2-p-p'}\right)(p+p'-1)^n\right)+1-p' = $$
$$\left(\frac{(1-p')(p+p'-1) + (1-p')(2-p-p')}{2-p-p'} + \left(\alpha - \frac{1-p'}{2-p-p'}\right)(p+p'-1)^n\right) = $$
$$\frac{(1-p')}{2-p-p'} + \left(\alpha - \frac{1-p'}{2-p-p'}\right)(p+p'-1)^n$$

Para os limites, temos que:

$$\lim \alpha_n = \frac{1-p'}{2-p-p'}$$
$$P_n = \alpha_np + (1-\alpha_n)p'$$
$$\lim P_n = \frac{p-pp'}{2-p-p'}+\frac{p'-pp'}{2-p-p'} = \frac{p+p'-2pp'}{2-p-p'}$$
### Exercício 18

$$\mathbb{P}(\text{chove no dia }n) = \mathbb{P}(\text{chove no dia }n-1)\mathbb{P}(\text{chove no dia }n|\text{chove no dia }n-1) + (1-\mathbb{P}(\text{chove no dia }n-1))\mathbb{P}(\text{chove no dia }n|\text{não chove no dia }n-1) = $$
$$\mathbb{P}(\text{chove no dia }n-1)(p - 1 +p) + 1-p.$$

Vamos provar por indução que 

$$P_n = \frac{1}{2} + \frac{1}{2}(2p-1)^n, n \geq 0.$$
1. Vale para $n = 0$

$$P_0 = \frac{1}{2} + \frac{1}{2}(2p-1)^0 = 1$$
2. Se vale para $n$, vale pare $n+1$:

$$P_{n+1} = (2p-1)\left(\frac{1}{2}+\frac{1}{2}(2p-1)^n\right) + 1-p = \frac{2-2p+2p-1}{2} + \frac{1}{2}(2p-1)^{n+1} = \frac{1}{2} + \frac{1}{2}(2p-1)^{n+1}$$
### Exercício 19

Considere o espaço de probabilidades $(\Omega = \{1,2,3,4,5,6\},\mathcal{P}(\mathbb{\Omega}), \mathbb{P}(\{i\} = 1/6))$. Tome $E_1 = \{1,2,3\}, E_2 = \{1,4\}, F = \{1,2,3,4\}$. Nessas condições $\mathbb{P}(E_1 \cap E_2) = \mathbb{P}(E_1)\mathbb{P}(E_2)$, mas $\mathbb{P}(E_1 \cap E_2 | F) = \frac{\mathbb{P}(\{1\})}{4/6} = 1/4 \neq \frac{3/6}{4/6}\frac{2/6}{4/6} = \frac{6}{16}$
